name: weather_app
description: Chapters 4 - 6, Flutter in Action by Eric Windmill
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.11.1

dev_dependencies:
  build_runner: ^2.2.0
  built_value_generator: ^8.4.0
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Regular.otf
        - asset: assets/fonts/Cabin-Bold.otf
        - asset: assets/fonts/Cabin-Italic.otf
        - asset: assets/fonts/Cabin-Medium.otf
        - asset: assets/fonts/Cabin-BoldItalic.otf
        - asset: assets/fonts/Cabin-MediumItalic.otf
        - asset: assets/fonts/Cabin-SemiBold.otf
        - asset: assets/fonts/Cabin-SemiBoldItalic.otf